# Copyright (C) Guya , PLC - All Rights Reserved (As Of Pending...)
# Unauthorized copying of this file, via any medium is strictly prohibited
# Proprietary and confidential
 
# This file is subject to the terms and conditions defined in
# file 'LICENSE.txt', which is part of this source code package.

# @author [Simon Belete](https://github.com/Simonbelete)
# @project Guya E-commerce & Guya Express
# @description Guya Project ocurstates

apiVersion: apps/v1

kind: Deployment

metadata:
  name: api-gateway

spec:
  selector:
    matchLabels:
      app: api-gateway

  template:
    metadata:
      labels:
        app: api-gateway
    
    spec:
      containers:
      - name: api-gateway
        image: guyaltd/api-gateway