global:
  postgresql:
    postgresqlDatabase: db_DAkF1V9jeX
    postgresqlUsername: user_56EMsY
    postgresqlPassword: 6ae6c09ca8

#postgresqlDatabase: db_DAkF1V9jeX
#postgresqlUsername: user_56EMsY
#postgresqlPassword: 6ae6c09ca8

#CREATE USER user_HeZ2g9X WITH PASSWORD 'd0d88d7f7e';
#CREATE DATABASE db_6kOj76I;
#GRANT ALL PRIVILEGES ON DATABASE db_6kOj76I TO user_HeZ2g9X;

initdbScripts:
  initdb.sh: |
    #!/bin/bash
    export POSTGRES_PASSWORD=6ae6c09ca8
    set -e

    PGPASSWORD="$POSTGRES_PASSWORD" psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
      CREATE DATABASE db_6koj76i;
    EOSQL


persistence:
  # Size of data volume
  size: 5Gi