#global:
#  postgresql:
#    postgresqlDatabase: db_DAkF1V9jeX
#    postgresqlUsername: user_56EMsY
#    postgresqlPassword: 6ae6c09ca8

postgresqlDatabase: db_DAkF1V9jeX
postgresqlUsername: user_56EMsY
postgresqlPassword: 6ae6c09ca8

initdbScripts:
  initdb.sh: |
    #!/bin/bash
    set -e

    psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
        # userdb
        CREATE USER user_HeZ2g9X WITH PASSWORD 'd0d88d7f7e';
        CREATE DATABASE db_6kOj76I;
        GRANT ALL PRIVILEGES ON DATABASE db_6kOj76I TO user_HeZ2g9X;

        # chatdb
        CREATE USER user_56EMsY WITH PASSWORD '5ae5c05ca1';
        CREATE DATABASE db_5k2j752;
        GRANT ALL PRIVILEGES ON DATABASE db_5k2j752 TO user_56EMsY;
    EOSQL

persistence:
  # Size of data volume
  size: 2Gi