apiVersion: v1
kind: Service
metadata:
  labels:
    app: logstash
  name: logstash-tcp
  namespace: guya-ltd
spec:
  ports:
  - name: tcp
    port: 5044
    protocol: TCP
    targetPort: 5044
  selector:
    app: logstash
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: logstash
  name: logstash-udp
  namespace: guya-ltd
spec:
  ports:
  - name: tcp
    port: 514
    protocol: UDP
    targetPort: 514
  selector:
    app: logstash
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: shop-web
  name: shop-web
  namespace: guya-ltd
spec:
  ports:
  - name: http
    port: 80
  selector:
    app: shop-web
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: logstash
  name: logstash
  namespace: guya-ltd
spec:
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: logstash
  template:
    metadata:
      labels:
        app: logstash
    spec:
      containers:
      - image: docker.elastic.co/logstash/logstash:7.6.1
        name: logstash
        volumeMounts:
        - mountPath: /usr/share/logstash/config
          name: pvc-logstash-volume
    volumes:
    - name: pvc-logstash-volume
      persistentVolumeClaim:
        claimName: pv-logstash
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: shop-web
  name: shop-web
  namespace: guya-ltd
spec:
  replicas: 2
  selector:
    matchLabels:
      app: shop-web
  template:
    metadata:
      labels:
        app: shop-web
    spec:
      containers:
      - image: guyaltd/shop-web
        name: shop-web
apiVersion: v1
kind: Service
metadata:
  labels:
    app: logstash
  name: logstash-tcp
  namespace: guya-ltd
spec:
  ports:
  - name: tcp
    port: 5044
    protocol: TCP
    targetPort: 5044
  selector:
    app: logstash
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: logstash
  name: logstash-udp
  namespace: guya-ltd
spec:
  ports:
  - name: tcp
    port: 514
    protocol: UDP
    targetPort: 514
  selector:
    app: logstash
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: shop-web
  name: shop-web
  namespace: guya-ltd
spec:
  ports:
  - name: http
    port: 80
  selector:
    app: shop-web
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: logstash
  name: logstash
  namespace: guya-ltd
spec:
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: logstash
  template:
    metadata:
      labels:
        app: logstash
    spec:
      containers:
      - image: docker.elastic.co/logstash/logstash:7.6.1
        name: logstash
        volumeMounts:
        - mountPath: /usr/share/logstash/config
          name: pvc-logstash-volume
    volumes:
    - name: pvc-logstash-volume
      persistentVolumeClaim:
        claimName: pv-logstash
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: shop-web
  name: shop-web
  namespace: guya-ltd
spec:
  replicas: 2
  selector:
    matchLabels:
      app: shop-web
  template:
    metadata:
      labels:
        app: shop-web
    spec:
      containers:
      - image: guyaltd/shop-web
        name: shop-web
apiVersion: v1
kind: Service
metadata:
  labels:
    app: logstash
  name: logstash-tcp
  namespace: guya-ltd
spec:
  ports:
  - name: tcp
    port: 5044
    protocol: TCP
    targetPort: 5044
  selector:
    app: logstash
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: logstash
  name: logstash-udp
  namespace: guya-ltd
spec:
  ports:
  - name: tcp
    port: 514
    protocol: UDP
    targetPort: 514
  selector:
    app: logstash
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: shop-web
  name: shop-web
  namespace: guya-ltd
spec:
  ports:
  - name: http
    port: 80
  selector:
    app: shop-web
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: logstash
  name: logstash
  namespace: guya-ltd
spec:
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: logstash
  template:
    metadata:
      labels:
        app: logstash
    spec:
      containers:
      - image: docker.elastic.co/logstash/logstash:7.6.1
        name: logstash
        volumeMounts:
        - mountPath: /usr/share/logstash/config
          name: pvc-logstash-volume
    volumes:
    - name: pvc-logstash-volume
      persistentVolumeClaim:
        claimName: pv-logstash
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: shop-web
  name: shop-web
  namespace: guya-ltd
spec:
  replicas: 2
  selector:
    matchLabels:
      app: shop-web
  template:
    metadata:
      labels:
        app: shop-web
    spec:
      containers:
      - image: guyaltd/shop-web
        name: shop-web
