# Copyright (C) Guya , PLC - All Rights Reserved (As Of Pending...)
# Unauthorized copying of this file, via any medium is strictly prohibited
# Proprietary and confidential
 
# This file is subject to the terms and conditions defined in
# file 'LICENSE.txt', which is part of this source code package.

# @author [Simon Belete](https://github.com/Simonbelete)
# @project Guya E-commerce & Guya Express
# @description Guya Project ocurstates

apiVersion: apps/v1

kind: Deployment

metadata:
  name: chipmunk

spec:
  selector:
    matchLabels:
      app: chipmunk

  template:
    metadata:
      labels:
        app: chipmunk
    
    spec:
      hostNetwork: true
      containers:
      - name: chipmunk
        image: guyaltd/chipmunk
        env:
        - name: MAILER_DSN
          value: "smtp://localhost:1025"
        - name: ACCOUNT_SENDER_EMAIL
          value: "admin@localhost.com"
        - name: SMTP_HOST
          value: "127.0.0.1"
        - name: SMTP_PORT
          value: "1025"
        - name: SMTP_USERNAME
          value: ""
        - name: SMTP_PASSWORD
          value: ""
        - name: RABBITMQ_HOST
          value: "127.0.0.1"
        - name: RABBITMQ_PORT
          value: "1025"
        - name: RABBITMQ_USERNAME
          value: "rabbitmq_user"
        - name: RABBITMQ_PASSWORD
          value: "0875e68ce5"
      - name: mailhog
        image: guyaltd/mailhog