# Copyright (C) Guya , PLC - All Rights Reserved (As Of Pending...)
# Unauthorized copying of this file, via any medium is strictly prohibited
# Proprietary and confidential
 
# This file is subject to the terms and conditions defined in
# file 'LICENSE.txt', which is part of this source code package.

# @author [Simon Belete](https://github.com/Simonbelete)
# @project Guya E-commerce & Guya Express
# @description Guya Project ocurstates

apiVersion: apps/v1

kind: Deployment

metadata:
  name: payment

spec:
  selector:
    matchLabels:
      app: payment

  template:
    metadata:
      labels:
        app: payment
    
    spec:
      containers:
      - name: payment
        image: guyaltd/payment
        #imagePullPolicy: Always
        env:
        - name: ENV 
          value: "dev"
        # Mongo DB Vars
        - name: MONGODB_USERNAME
          value: "user_9hOfBET"
        - name: MONGODB_PASSWORD
          value: "d8fc7a94fb"
        - name: MONGODB_DB
          value: "db_fmqFcq0"
        - name: MONGODB_HOST
          value: "mongodb-headless.guya-ltd.svc.cluster.local"
        - name: MONGODB_PORT
          value: "27017"
        # Production Env
        - name: HOST
          value: "0.0.0.0"
        - name: PORT
          value: "5000"
        # Flask Development ENV
        - name: FLASK_APP
          value: "payment"
        - name: FLASK_ENV
          value: "development"
        - name: FLASK_RUN_HOST
          value: "0.0.0.0"
        - name: FLASK_RUN_PORT
          value: "5000"
        # Logstash Logging Vars
        - name: LOGGING_HOST
          value: "logstash-logstash.guya-ltd-elk.svc.cluster.local"
        - name: LOGGING_PORT
          value: "5400"
        # URL endpoints
        - name: GATEKEEPER_URL
          value: "gatekeeper.guya-ltd.svc.cluster.local"
        - name: CHIPMUNK_URL
          value: "chipmunk.guya-ltd.svc.cluster.local"
        - name: ORDER_URL
          value: "order.guya-ltd.svc.cluster.local"
        - name: MOCKING_SERVER_URL
          value: "mocking-server.guya-ltd.svc.cluster.local"
