auth:
  rootPassword: ea6faee84c
  username: user_89Tw15W
  password: 7ad89b9279
  database: db_u7SqbAA

initdbScripts:
  initdb.js: |
    // Branch db
    use db_8j2m19h
    // Cart db
    use db_JqC11r
    // Payment db
    use db_fmqFcq0

    // Branch User
    db.createUser(
      {
        user : "user_P0SN5bH",
        pwd  : "c2b0801598",
        roles : [
          {
            role : "readWrite",
              db : "db_8j2m19h"
          }
        ]
      }
    )

    // Cart User
    db.createUser(
      {
        user : "user_op0Mer",
        pwd  : "ff8c886615",
        roles : [
          {
            role : "readWrite",
              db : "db_JqC11r"
          }
        ]
      }
    )

    // Payment user
    db.createUser(
      {
        user : "user_9hOfBET",
        pwd  : "d8fc7a94fb",
        roles : [
          {
            role : "readWrite",
              db : "db_fmqFcq0"
          }
        ]
      }
    )

# Set to true to use StatefulSet instead of Deployment even when replicaSet.enalbed=false
useStatefulSet: true

metrics:
  # Start a side-car prometheus exporter
  enabled: true

service:
  # MongoDB service port
  port: 27017

replicaSet:
  # Switch to enable/disable replica set configuration
  enabled: false

persistence:
  # Size of data volume
  size: 10Gi